### ISSUE TITLE
Can't use mysql host name in .env file

### ISSUE THREAD

**Issue by afrilianarief** [remp2020/remp#148]
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select * from information_schema.tables where table_schema = sso and table_name = migrations and table_type = 'BASE TABLE')

**Comment by markoph** [comment]
Thank you for the error. But we need more details to help with debugging.

- How do you run it? With our Docker / DockerCompose configuration? Or do you run some of the services differently (eg. outside of Docker / in you own Docker service)?
- What did you put in MySQL host in `.env`?
