### ISSUE TITLE
Errors at the start when make docker-build

### ISSUE THREAD

**Issue by A-linea** [remp2020/remp#229]
Hello thank you for your work.
First of all, I would like to ask:  Is it realistic install this project from a docker to m2 chip macos. I saw several images that are not compatible.

After that I switched to Ubuntu v 22.04. 
Docker v 24.0.6 build ed223bc
When I run make docker-build

```
❯ make docker-build
cd "Beam" && make docker-build
make[1]: Entering directory '/var/www/remp/Beam'
make[2]: Entering directory '/var/www/remp/Beam/go/cmd/tracker'
set -e; \
docker build -t remp-beam_tracker_builder builder; \
docker run -e TARGET_GOOS -e TARGET_GOARCH -e TARGET_SUFFIX --rm -v $PWD/../../:/src/build remp-beam_tracker_builder > tracker.tar;
[+] Building 2.2s (13/13) FINISHED                         docker:desktop-linux
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 314B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/golang:1.20.5           2.0s
 => [auth] library/golang:pull token for registry-1.docker.io              0.0s
 => [1/7] FROM docker.io/library/golang:1.20.5@sha256:fd9306e1c664bd49a11  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 206B                                          0.0s
 => CACHED [2/7] RUN go install golang.org/x/tools/cmd/goimports@latest    0.0s
 => CACHED [3/7] RUN mkdir -p /src/build                                   0.0s
 => CACHED [4/7] RUN mkdir -p /go/src/gitlab.com/remp/remp/Beam/go         0.0s
 => CACHED [5/7] WORKDIR /go/src/gitlab.com/remp/remp/Beam/go              0.0s
 => CACHED [6/7] COPY build /usr/local/bin/                                0.0s
 => CACHED [7/7] RUN chmod +x /usr/local/bin/build                         0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:17ccc1c8e34c175caee653bf26b7dd049955a3c0ed7d3  0.0s
 => => naming to docker.io/library/remp-beam_tracker_builder               0.0s

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
/usr/local/bin/build: line 5: cd: cmd/tracker: No such file or directory
tar: tracker: Cannot stat: No such file or directory
tar: swagger: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
make[2]: *** [Makefile:40: docker-build] Error 2
make[2]: Leaving directory '/var/www/remp/Beam/go/cmd/tracker'
make[1]: *** [Makefile:60: docker-build] Error 2
make[1]: Leaving directory '/var/www/remp/Beam'
make: *** [Makefile:68: docker-build] Error 2

```
Permissons for www 775 $USER:$USER
$User added to docker group
Maybe i miss something. Can anyone help, please?

**Comment by A-linea** [comment]
UPD: Seted permissions 777 on the folder with remp. This part is working

**Comment by rootpd** [comment]
Hi, thanks for the update regarding permissions. We've tested this some time ago with M1 macs and didn't find any of these issues, but we'll do another round of testing. This is the first time we see anything regarding permissions and Docker build.

Btw. if you're starting with the clean installation, we're in the process of separating apps from this monorepo to separatate applications and making them extendable. We've managed to extract Mailer and Beam so far:

- https://github.com/remp2020/mailer-skeleton/
- https://github.com/remp2020/beam-skeleton
- https://github.com/remp2020/crm-skeleton/ (this was always separate, I'm listing it here just for the sake of completeness)

I recommend to start with them. They still need SSO which needs to be run from this monorepo, but you don't need to run everything from this monorepo anymore.

**Comment by A-linea** [comment]
Thank you for your response. Yes, that's right, we need both remp and CRM, but if I understood correctly, then what if I deploy only the CRM skeleton and add the modules that I need myself, it still needs remp.

**Comment by rootpd** [comment]
The CRM (deployed as skeleton) can live completely on its own, without other REMP tools (Mailer/SSO/Campaign/Beam). Though you might need Mailer (or some other integration directly in CRM) if you want to send emails :).

The issue you see is caused by an error we introduced in 2.9. We've already fixed it (https://github.com/remp2020/crm-users-module/releases/tag/2.9.2), please run `composer update` to update your CRM modules to the latest version.
