### ISSUE TITLE
Support Segment exclusion in Campaign

### ISSUE THREAD

**Issue by rootpd** [remp2020/remp#29]
**In the UI**

The current selectbox needs to be replaced with something more advanced. Users need to be able to state whether they want to _include_ people of segments or _exclude_ and select specific segment.

It should be therefore possible to configure campaign in a way that:

* Includes users of segment `Foo`
* Excludes users of segment `Bar`

The way how it should be done visually is still open.

**In the backend**

The actual exclusion/inclusion should happen with a flag in `campaign_segments` relation table. Frontend form `CampaignForm.vue` component and backend `CampaignRequest` class needs to be altered to reflect these changes so they editable.

The check when the banner is displayed should be done both in `CampaignController::showtime()` and in `public/showtime.php` (experimental implementation bypassing Laravel).

**Comment by brunodelgado1988** [comment]
How can I be assigned to this Issue?

**Comment by brunodelgado1988** [comment]
Implemented at [Pull Request #33](https://github.com/remp2020/remp/pull/33)
