### ISSUE TITLE
Failure while running install.sh

### ISSUE THREAD

**Issue by jigar1101** [remp2020/remp#3]
The docker build is failing for the `adminer` service where yarn is being installed.

`RUN curl -sL https://yarnpkg.com/install.sh | bash -`

![yarninstall](https://user-images.githubusercontent.com/3745587/41538326-bb137fae-7328-11e8-83ce-15adba7facbc.png)

I've tried writing it into a file and then running it, which worked.

**Comment by rootpd** [comment]
Hi, what OS are you on?

**Comment by jigar1101** [comment]
@rootpd I'm on Mac
