### ISSUE TITLE
Duplicated data on Article - Pageview Stats

### ISSUE THREAD

**Issue by brunodelgado1988** [remp2020/remp#30]
We noticed that there's duplicated data on Article - Pageview Stats when we apply some query conditions.

![Screenshot from 2019-10-07 11-26-05](https://user-images.githubusercontent.com/2372140/66304514-44c67880-e8f5-11e9-8fd1-3bc039939770.png)

They have the same id in each of the repeated article.

**Steps to Reproduce:**
1. Go to Pageview Stats in Beam;
2. Filter by published date: Last 2 Days
3. Order by All Pageviews (Descending)

**Comment by rootpd** [comment]
Confirmed. The duplication happens due to incorrect join on authors. We'll refactor.
