### ISSUE TITLE
Copy paste error ?

### ISSUE THREAD

**Issue by SachaMorard** [remp2020/remp#39]
Hello

It seems that an url landed quietly here https://github.com/remp2020/remp/blob/master/Beam/app/Http/Controllers/AuthorController.php#L140

Best ;)
Sacha

**Comment by rootpd** [comment]
Ouch :). For a while I thought our CI job for syntax check is broken, but looks like that's a still valid syntax!

* `http:` is a "go to" label
* `//...` is a comment

It's fixed, thanks.
