### ISSUE TITLE
Potential import collision: import path should be "github.com/sirupsen/logrus", not "github.com/Sirupsen/logrus"

### ISSUE THREAD

**Issue by KateGo520** [remp2020/remp#83]
## Background
The `sirupsen/logrus` has already renamed it’s import path from "github.com/Sirupsen/logrus" to "github.com/sirupsen/logrus".
As [README](https://github.com/sirupsen/logrus/blob/v1.0.4/README.md) of logrus said, `github.com/Sirupsen/logrus` is the old path, anything using it should be updated to `github.com/sirupsen/logrus`.

> Some environments experienced problems with the upper-case variant, so the lower-case was decided. Everything using `logrus` will need to use the lower-case: `github.com/sirupsen/logrus`. Any package that isn't, should be changed.

But `remp2020/remp` still used the old path:
https://github.com/remp2020/remp/blob/master/Beam/go/Gopkg.lock#L26
```
[[projects]]
  digest = "1:42a42c4bc67bed17f40fddf0f24d4403e25e7b96488456cf4248e6d16659d370"
  name = "github.com/Sirupsen/logrus"
  packages = ["."]
  pruneopts = ""
  revision = "d682213848ed68c0a260ca37d6dd5ace8423f5ba"
  version = "v1.0.4"
```
When you use the old path "github.com/Sirupsen/logrus" to import the `logrus`, it will be very easy to reintroduce `logrus` through the import statements "import github.com/sirupsen/logrus" in the go source file of `logrus`.
https://github.com/remp2020/remp/blob/master/Beam/go/vendor/github.com/Sirupsen/logrus/hooks/syslog/syslog.go
```
package syslog
import (
	"fmt"
	"log/syslog"
	"os"
	"github.com/sirupsen/logrus"
))
…
```
The "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus" are the same repos. This will work in isolation, bring about potential risks and problems.

## Solution
Replace all the old import paths, change `"github.com/Sirupsen/logrus"` to `"github.com/sirupsen/logrus"`.
Where did you import it: https://github.com/remp2020/remp/search?q=github.com%2FSirupsen%2Flogrus&unscoped_q=github.com%2FSirupsen%2Flogrus

**Comment by KateGo520** [comment]
@miroc  @rootpd  Could you help me review this issue? Thx :p

**Comment by rootpd** [comment]
Thanks for the report. We've changed the import paths ~2 months ago, just forgot to mention it here.
